export const POSITION_LOCATIONS = {
  1: ['', '', 'GK', '', ''],
  2: ['', '', 'SW', '', ''],
  3: ['LB', 'LCB', 'CB', 'RCB', 'RB'],
  4: ['LWB', 'LDM', 'CDM', 'RDM', 'RWB'],
  5: ['LM', 'LCM', 'CAM', 'RCM', 'RM'],
  6: ['', 'LAM', 'AM', 'RAM', ''],
  7: ['LF', 'LCF', 'CF', 'RCF', 'RF'],
  8: ['LW', 'LS', 'ST', 'RS', 'RW'],
};

export const POSITION_TABLE: { [key: number]: string } = {
  0: 'GK',
  1: 'SW',
  2: 'RWB',
  3: 'RB',
  4: 'RCB',
  5: 'CB',
  6: 'LCB',
  7: 'LB',
  8: 'LWB',
  9: 'RDM',
  10: 'CDM',
  11: 'LDM',
  12: 'RM',
  13: 'RCM',
  14: 'CM',
  15: 'LCM',
  16: 'LM',
  17: 'RAM',
  18: 'CAM',
  19: 'LAM',
  20: 'RF',
  21: 'CF',
  22: 'LF',
  23: 'RW',
  24: 'RS',
  25: 'ST',
  26: 'LS',
  27: 'LW',
  28: 'SUB',
};
